from dataclasses import dataclass


@dataclass(frozen=True)
class ValueObject:
    """Immutable value object base. Equality by all fields — generated by @dataclass(frozen=True)."""
    # ponytail: no custom __eq__/__hash__ — @dataclass(frozen=True) generates correct
    # per-subclass equality, which is stricter and safer than isinstance-based comparison.


@dataclass(frozen=True)
class _DemoMoney(ValueObject):
    amount: int
    currency: str


def _demo():
    a = _DemoMoney(100, "CNY")
    b = _DemoMoney(100, "CNY")
    c = _DemoMoney(200, "CNY")
    assert a == b, "same values should be equal"
    assert a != c, "different values should not be equal"
    assert hash(a) == hash(b), "equal objects should have equal hash"
    print("base_value_object: OK")


if __name__ == "__main__":
    _demo()
