from dataclasses import dataclass


@dataclass(frozen=True)
class ValueObject:
    """Immutable value object base. Equality by all fields — generated by @dataclass(frozen=True)."""
    # ponytail: no custom __eq__/__hash__ — @dataclass(frozen=True) generates correct
    # per-subclass equality, which is stricter and safer than isinstance-based comparison.
