from tortoise import fields, migrations
from tortoise.migrations import operations as ops


class Migration(migrations.Migration):
    operations = [
        ops.CreateModel(
            name="AlertRuleModel",
            fields=[
                ("id", fields.IntField(primary_key=True)),
                ("code", fields.CharField(max_length=64, unique=True)),
                ("name", fields.CharField(max_length=100)),
                ("metric", fields.CharField(max_length=64)),
                ("operator", fields.CharField(max_length=8)),
                ("threshold", fields.DecimalField(max_digits=18, decimal_places=4)),
                ("level", fields.CharField(max_length=16, default="warning")),
                ("enabled", fields.BooleanField(default=True)),
                ("consecutive_triggers", fields.IntField(default=1)),
                ("auto_resolve", fields.BooleanField(default=True)),
                ("created_at", fields.DatetimeField(auto_now_add=True)),
                ("updated_at", fields.DatetimeField(auto_now=True)),
            ],
            options={"table": "alert_rules", "app": "models", "pk_attr": "id"},
            bases=["Model"],
        ),
        ops.CreateModel(
            name="AlertModel",
            fields=[
                ("id", fields.IntField(primary_key=True)),
                ("project_id", fields.IntField(index=True)),
                ("rule_code", fields.CharField(max_length=64, index=True)),
                ("alert_type", fields.CharField(max_length=64)),
                ("level", fields.CharField(max_length=16, index=True)),
                ("title", fields.CharField(max_length=200)),
                ("message", fields.TextField()),
                ("metric_value", fields.DecimalField(max_digits=18, decimal_places=4)),
                ("threshold_value", fields.DecimalField(max_digits=18, decimal_places=4)),
                ("ym", fields.CharField(max_length=7, null=True, index=True)),
                ("status", fields.CharField(max_length=20, default="active", index=True)),
                ("fingerprint", fields.CharField(max_length=160, index=True)),
                ("trigger_count", fields.IntField(default=1)),
                ("first_triggered_at", fields.DatetimeField()),
                ("last_triggered_at", fields.DatetimeField()),
                ("acknowledged_by", fields.IntField(null=True)),
                ("acknowledged_at", fields.DatetimeField(null=True)),
                ("resolved_by", fields.IntField(null=True)),
                ("resolved_at", fields.DatetimeField(null=True)),
                ("resolution_note", fields.TextField(null=True)),
                ("ignored_until", fields.DatetimeField(null=True)),
                ("created_at", fields.DatetimeField(auto_now_add=True)),
                ("updated_at", fields.DatetimeField(auto_now=True)),
            ],
            options={"table": "alerts", "app": "models", "pk_attr": "id",
                     "indexes": (("project_id", "status"), ("fingerprint", "status"))},
            bases=["Model"],
        ),
        ops.CreateModel(
            name="AlertEventModel",
            fields=[
                ("id", fields.IntField(primary_key=True)),
                ("alert_id", fields.IntField(index=True)),
                ("event_type", fields.CharField(max_length=32)),
                ("actor_id", fields.IntField(null=True)),
                ("note", fields.TextField(null=True)),
                ("snapshot", fields.JSONField(default=dict)),
                ("created_at", fields.DatetimeField(auto_now_add=True)),
            ],
            options={"table": "alert_events", "app": "models", "pk_attr": "id"},
            bases=["Model"],
        ),
        ops.CreateModel(
            name="AlertRuleStateModel",
            fields=[
                ("id", fields.IntField(primary_key=True)),
                ("project_id", fields.IntField(index=True)),
                ("rule_code", fields.CharField(max_length=64)),
                ("scope", fields.CharField(max_length=16)),
                ("consecutive_count", fields.IntField(default=0)),
                ("updated_at", fields.DatetimeField(auto_now=True)),
            ],
            options={"table": "alert_rule_states", "app": "models", "pk_attr": "id",
                     "unique_together": (("project_id", "rule_code", "scope"),)},
            bases=["Model"],
        ),
        ops.CreateModel(
            name="AlertOutboxModel",
            fields=[
                ("id", fields.IntField(primary_key=True)),
                ("event_type", fields.CharField(max_length=64)),
                ("aggregate_id", fields.IntField(index=True)),
                ("project_id", fields.IntField(index=True)),
                ("payload", fields.JSONField()),
                ("status", fields.CharField(max_length=16, default="pending", index=True)),
                ("retry_count", fields.IntField(default=0)),
                ("next_retry_at", fields.DatetimeField(null=True)),
                ("sent_at", fields.DatetimeField(null=True)),
                ("last_error", fields.TextField(null=True)),
                ("created_at", fields.DatetimeField(auto_now_add=True)),
            ],
            options={"table": "alert_outbox", "app": "models", "pk_attr": "id"},
            bases=["Model"],
        ),
    ]
